parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     vsftpd
    database_user:     root
    database_password: meta10

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            fr
    secret:            ThisTokenIsNotSoSecretChangeIt
    
    admin_password: 1234
    path_folder:  /var/ftp
    inside_path: www
