Fastre\PhpFtpAdminBundle\Entity\Account:
    properties:
        username:
            - Regex: 
                pattern: "/^[a-zA-Z0-9]+$/"
                message: "Le nom d'utilisateur ne peut contenir que des lettres minuscules et majuscules et des chiffres."
                groups: [registration, update]
        pass: 
            - Length: 
                min: 8
                minMessage: "Votre mot de passe doit contenier {{ limit }} caractères."
                groups: [registration, update]
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: {fields: [username], groups: [registration]}
        
